### ISSUE TITLE
Inventory Sort

### ISSUE THREAD

**Issue by gameboycjp** [Nutcake/ReCon#10]
I'd like the option to change how inventory sorting works. I think the best case scenario would be sorting items of the same name by date, but even just a toggle to sort everything purely by date would be enough.

**Comment by Nutcake** [comment]
Added in 2d785d6cb422ecfda66d7d8305d0eddbed48fa28

**Comment by gameboycjp** [comment]
Awesome, thank you, I was finally able to clean up around 400 old versions of my avatars!
