### ISSUE TITLE
Start Invisible 

### ISSUE THREAD

**Issue by troyBORG** [Nutcake/ReCon#11]
Is there a way I can make it so it will open as invisible so if I view it a work my friends aren't notified I'm online and think I'm free to hang out.

**Comment by Nutcake** [comment]
The app used to save and restore your last online status, but I guess that's broken now. I'll fix this as soon as I can. 

Do note that the app also sets your status to be "Online on version xx.yy.zz of ReCon" so your friends should be able to see that you're not actually online in game.
