### ISSUE TITLE
ReCon status

### ISSUE THREAD

**Issue by Krzeszny** [Nutcake/ReCon#32]
When you're using ReCon, you have the status "Online on version 0.11.1-beta of ReCon" but displaying the version number isn't practical, while uninformed users still wonder what ReCon is.

I suggest modifying the status to something such as:
1. Online on ReCon app by Nutcake
2. Using ReCon app by Nutcake
The addition of "by Nutcake" makes it googlable. Otherwise, there are many apps called Recon.

Small bug:
I've noticed that my status sometimes displays ReCon (didn't check if others also see it) when I launch Resonite while using Recon.

**Comment by isovel** [comment]
> Small bug:
I've noticed that my status sometimes displays ReCon (didn't check if others also see it) when I launch Resonite while using Recon.

That's not on our end; it happens when Resonite's servers decide to use the status provided by ReCon, rather than the one broadcasted by the actual client.

**Comment by isovel** [comment]
> When you're using ReCon, you have the status "Online on version 0.11.1-beta of ReCon" but displaying the version number isn't practical, while uninformed users still wonder what ReCon is.
> 
> I suggest modifying the status to something such as:
> 
> Online on ReCon app by Nutcake
> Using ReCon app by Nutcake
> The addition of "by Nutcake" makes it googlable. Otherwise, there are many apps called Recon.

This also isn't easily possible. The app abuses the reported version field to show it in the first place, so Resonite will always show "on version" when displaying ReCon's status using the current method.

**Comment by XDelta** [comment]
As of `2024.7.19.281` Bot and Chat Client user statuses are now displayed in the contacts list. These will show as 
`Chat client: 0.11.1-beta of ReCon`

**Comment by XDelta** [comment]
This does make it more searchable as a result
![257adc07cf](https://github.com/user-attachments/assets/f9fbfba3-58dd-4bf2-a6b5-9c8df76d2cc1)
Although `Resonite recon` is also enough to find the github as well

**Comment by Nutcake** [comment]
As isovel already said there is no way to actually implement these changes and I don't see much of a reason to do so anyways as a bit of determined googling will get you what you need.

**Comment by XDelta** [comment]
From the chat client status change in game, changing anything here probably isn't needed anymore anyway
