### ISSUE TITLE
Screenshots not loading

### ISSUE THREAD

**Issue by ArchieTheRaccoon** [Nutcake/ReCon#8]
Screenshots do not load in the chat (the received ones)
![Screenshot_20231011-094915](https://github.com/Nutcake/ReCon/assets/71369501/14ee87f8-3574-478d-8d7e-911473ea118a)

**Comment by Nutcake** [comment]
How was this screenshot sent from the other user?
This seems to work on my machine. When grabbing a picture in Resonite and dragging it into the chat input field, it displays completely fine in the app. The sent file might have been an invalid filetype?

**Comment by ArchieTheRaccoon** [comment]
Turns out this screenshot was made with the build of ReCon app when it didnt have that block that didnt let others upload screenshots by my friend. That's why it wasn't showing in the app x3 When I checked the screenshots in the Resonite itself - I couldnt see it as well. So yeah, its not a issue of this app

**Comment by Zeitheron** [comment]
Hopping here to comment that this image was sent using a self-build earlier version of this app, that would most likely explain the cause of this issue.

**Comment by Nutcake** [comment]
I see, that makes sense. 

Well technically this is still an issue with the app but it's already tracked in #4 :p

Thank you for following up on this.
